### ISSUE TITLE
How/where to add a new custom backend layout?

### ISSUE THREAD

**Issue by metaxos** [cedricziel/bootstrap_package_overrides#1]
H @cedricziel 

Thank you for this work.
For a new project I would like to use bootstrap_package. In this new project I need a new backend layout. I understood now, that the really correct way would be to leave the bootstrap_package untouched. So then I can take bootstrap_package_overrides to do my adaptions.
Sorry for my confusion but is my assumption also valid for a new backend layout? Would this be done in bootstrap_package_overrides?

Thank you for bringing my back on the right track :)

**Comment by cedricziel** [comment]
You may start here: https://github.com/cedricziel/bootstrap_package_overrides#example-include-a-custom-backend-layout-with-a-custom-template

Cheers,
Cedric
